name: recipe_finder_flutter_application
description: A recipe finder application built with Flutter and Riverpod.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # HTTP Client
  http: ^1.2.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Local DB
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  path: ^1.8.3

  # Persist simple flags
  shared_preferences: ^2.1.1

  # Image caching
  cached_network_image: ^3.2.4

  # UI
  flutter_svg: ^2.0.7

  # Utility
  cupertino_icons: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1